name: nyetop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  flutter_svg_provider: ^1.0.7
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  http: ^1.4.0
  cloud_firestore: ^5.6.7
  image_picker: ^1.0.4
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/onBoard1.png
    - assets/images/google_icon.png
    - assets/images/lock.svg
    - assets/images/profile.svg
    - assets/images/maki_arrow.svg
    - assets/icons/nonactive/
    - assets/icons/active/
    - assets/images/
    - assets/images/img_profile.png
    - assets/icons/png/ic_edit_profile.png
    - assets/icons/png/ic_logout.png
    - assets/icons/png/ic_history.png
    - assets/icons/nonactive/save.svg
    - assets/icons/png/ic2_profile.png
    - assets/icons/png/ic2_logout.png
    - assets/icons/png/ic2_item.png
    - assets/icons/png/ic2_wishlist.png
    - assets/icons/png/ic2_history.png

flutter_native_splash:
  color: "#060a56" 
  image: assets/images/wlogo.png 
  android_12:
    image: assets/images/wlogo.png
    color: "#060a56"
